apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployAN
  labels:
    app: autodeployAN
  namespace: namespace-workflow-1714637076981
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployAN
  template:
    metadata:
      labels:
        app: autodeployAN
    spec:
      containers:
        - name: autodeployAN
          image: acrworkflow1714637076981.azurecr.io/image-workflow-1714637076981:latest
          ports:
            - containerPort: 5000