apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployNA
  labels:
    app: autodeployNA
  namespace: namespace-workflow-1715068242241
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployNA
  template:
    metadata:
      labels:
        app: autodeployNA
    spec:
      containers:
        - name: autodeployNA
          image: acrworkflow1715068242241.azurecr.io/image-workflow-1715068242241:latest
          ports:
            - containerPort: 5000