apiVersion: v1
kind: Service
metadata:
  name: autodeployNA
  namespace: namespace-workflow-1715068242241
spec:
  type: LoadBalancer
  selector:
    app: autodeployNA
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000