apiVersion: v1
kind: Service
metadata:
  name: autodeployAN
  namespace: namespace-workflow-1714637076981
spec:
  type: LoadBalancer
  selector:
    app: autodeployAN
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000